easy peasy lemon squeeze
mate-academy/js_task-transportation-on-vacation pull request #1211
Opened 2022-03-28 13:22 UTC by Havrysh

2022-03-29 08:07 UTC, ArturErmolenko requested changes
You have a repeating expression - days * 40
Better put it in a separate variable

2022-03-30 15:33 UTC, vkryvytskyy commented on src/calculateRentalCost.js
> +  } else if (days >= 3 && days < 7) {
```suggestion
  } else if (days < 7) {
```
Ты уже проверил что days >= 3 предыдущем if

2022-03-31 07:01 UTC, ArturErmolenko requested changes

2022-03-31 07:01 UTC, ArturErmolenko commented on src/calculateRentalCost.js
> +    amount = amountOfDays - 20;
вынеси discounts в переменные

2022-03-31 07:01 UTC, ArturErmolenko commented on src/calculateRentalCost.js
> +    amount = amountOfDays - 50;
same

2022-03-31 07:56 UTC, ArturErmolenko approved these changes
👍

2024-12-11 13:40 UTC, closed without merging