solution
mate-academy/js_task-transportation-on-vacation pull request #1222
Opened 2022-03-30 08:55 UTC by OleksandrNi

2022-03-30 12:54 UTC, KostiaO commented
Хорошее решение, но можно было упростить...

2022-03-30 13:05 UTC, Anna-Tkachenko requested changes
Check all points from checklist

2022-03-30 13:45 UTC, OleksandrNi commented
add variables

2022-03-30 16:15 UTC, Anna-Tkachenko requested changes

2022-03-30 16:15 UTC, Anna-Tkachenko commented on src/calculateRentalCost.js
> +  }
You should create variables for 20 and 50 numbers, now I can't understand their meaning
And check point 3 in checklist (good example of returning value from if statement)

2022-03-31 10:05 UTC, Anna-Tkachenko approved these changes

2022-03-31 10:05 UTC, Anna-Tkachenko commented on src/calculateRentalCost.js
> +  }
else is redundant here (point 3 in checklist)
```suggestion
  if (days > 6) {
    return sum - bigDiscount;
  }
  
  if (days > 2) {
    return sum - smallDiscount;
  }
  
```

2023-03-15 15:36 UTC, closed without merging