train example
mate-academy/js_task-transportation-on-vacation pull request #1344
Opened 2022-05-05 18:44 UTC by NikitaKarbazin

Hi, i know about ternary operator, thats bad practice to put in `return` statement. But it really short code.

2022-05-13 11:31 UTC, mgrinko requested changes
Watch this https://youtu.be/tpB5vtFGcrg

2022-06-06 07:07 UTC, illiarerun requested changes
Nice start, now let's work on some fixes:

2022-06-06 07:07 UTC, illiarerun commented on src/calculateRentalCost.js
> +  }
[Checklist](https://github.com/mate-academy/js_task-transportation-on-vacation/blob/master/checklist.md) 1st item. You should create variables for main values - 20, 50, 40 they shouldn't be just magic numbers

2022-06-06 07:07 UTC, illiarerun commented on src/calculateRentalCost.js
> +  }
Also, checklist 3rd item, why do you have else if after a return statement? Code won't execute past this, use plain if construction

2022-06-09 07:25 UTC, illiarerun approved these changes
Gj, but I wouldn't use switch statement here

2023-10-07 15:39 UTC, closed without merging