Solution
mate-academy/js_task-transportation-on-vacation pull request #1430
Opened 2022-06-06 12:35 UTC by olya-yevsieienko

2022-06-06 14:26 UTC, YarinKiri2l approved these changes
Good Job!

2022-06-06 19:39 UTC, illiarerun requested changes
GJ, let's work on fixes now:

2022-06-06 19:39 UTC, illiarerun commented on src/calculateRentalCost.js
> +  }
[Checklist](https://github.com/mate-academy/js_task-transportation-on-vacation/blob/master/checklist.md?rgh-link-date=2022-06-06T18%3A50%3A47Z) 1st item. You should create variables for main values - 20, 50, 40, 3, 7 they shouldn't be just magic numbers

2022-06-06 21:17 UTC, olya-yevsieienko commented
I got it, thanks!

пн, 6 июн. 2022 г. в 22:39, Illia Vovchenko ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> GJ, let's work on fixes now:
> ------------------------------
>
> In src/calculateRentalCost.js
> <https://github.com/mate-academy/js_task-transportation-on-vacation/pull/1430#discussion_r890486316>
> :
>
> > +  if (days >= 7) {
> +    return rentalDays - 50;
> +  }
> +
> +  if (days >= 3) {
> +    return rentalDays - 20;
> +  }
>
> Checklist
> <https://github.com/mate-academy/js_task-transportation-on-vacation/blob/master/checklist.md?rgh-link-date=2022-06-06T18%3A50%3A47Z>
> 1st item. You should create variables for main values - 20, 50, 40, 3, 7
> they shouldn't be just magic numbers
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mate-academy/js_task-transportation-on-vacation/pull/1430#pullrequestreview-997116878>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO2L24MX5F4VIRMGA6RSCKDVNZHW5ANCNFSM5X7H2JHQ>
> .
> You are receiving this because you authored the thread.Message ID:
> <mate-academy/js_task-transportation-on-vacation/pull/1430/review/997116878
> @github.com>
>

2022-06-07 07:37 UTC, illiarerun requested changes

2022-06-07 07:37 UTC, illiarerun commented on src/calculateRentalCost.js
> +  const discountSevenDays = 50;
[Checklist](https://github.com/mate-academy/js_task-transportation-on-vacation/blob/master/checklist.md) 5th item, you shouldn't hardcode any values in variable names

2022-06-07 12:51 UTC, illiarerun approved these changes
GJ 🔥

2022-12-07 11:14 UTC, closed without merging