first commit
mate-academy/js_task-transportation-on-vacation pull request #1453
Opened 2022-06-13 14:10 UTC by pavel-gutsal

all seem`s to be ok

2022-06-15 12:10 UTC, aliceblunt8 requested changes

2022-06-15 12:10 UTC, aliceblunt8 commented on src/calculateRentalCost.js
> +  };
use variable in such cases, not function

```suggestion
  const total = days * 40;
```

2022-06-15 13:06 UTC, pavel-gutsal commented
My bad , stupid mistake of mine , now code is fixed

2022-06-16 13:07 UTC, ArtemTopolskyi requested changes

2022-06-16 13:07 UTC, ArtemTopolskyi commented on src/calculateRentalCost.js
> +  }
create separate variable for every number in the task

2022-06-17 14:37 UTC, aliceblunt8 approved these changes

2022-06-21 07:57 UTC, ArturErmolenko approved these changes

2022-10-07 11:25 UTC, closed without merging