Solution
mate-academy/js_task-transportation-on-vacation pull request #1497
Opened 2022-07-03 13:25 UTC by Kras4iy

2022-07-03 13:51 UTC, TwoAndMore requested changes

2022-07-03 13:51 UTC, TwoAndMore commented on src/calculateRentalCost.js
> +  return days * rentCost - 20;
Delete magic numbers

2022-07-03 14:06 UTC, TwoAndMore reviewed
Good job

2022-07-04 07:14 UTC, VETALEK requested changes
Good start 💪

2022-07-04 07:14 UTC, VETALEK commented on src/calculateRentalCost.js
> +  }
```suggestion
  if (days <= daysBeforeMinSale) {
    return days * rentCost;
  }
  
  if (days > daysBeforeMaxSale) {
    return days * rentCost - maxSale;
  }
```

you don't need `else`, cause `return` finishes the function execution when called

2022-07-04 07:53 UTC, VETALEK approved these changes
👍

2026-04-28 18:08 UTC, closed without merging