Initial solution
mate-academy/js_task-transportation-on-vacation pull request #1586
Opened 2022-07-27 13:43 UTC by MihailKostov

2022-07-31 16:04 UTC, ArtemTopolskyi requested changes

2022-07-31 16:04 UTC, ArtemTopolskyi commented on src/calculateRentalCost.js
> +  } else if (days < 7) {
нет необходимости в else конструкции, внутри if return

2022-08-03 13:45 UTC, valerii-derkach requested changes

2022-08-03 13:45 UTC, valerii-derkach commented on src/calculateRentalCost.js
>  }
```suggestion
  }
    return (costOfRent * days) - sevenDayOff;
}
```

2022-08-08 14:25 UTC, alexandra-protyanova approved these changes

2026-03-23 18:19 UTC, closed without merging