Solution
mate-academy/js_task-transportation-on-vacation pull request #1697
Opened 2022-08-15 16:29 UTC by nicatino

2022-08-16 10:45 UTC, oablokhina requested changes

2022-08-16 10:45 UTC, oablokhina commented on src/calculateRentalCost.js
> +    return days * 40;
add a variable with this value, because you use it several times

2022-08-18 15:39 UTC, oablokhina commented on src/calculateRentalCost.js
> +    return days * 40;
add days * 40 value to a variable, and then use it.

2022-08-18 15:39 UTC, oablokhina requested changes

2022-08-18 15:39 UTC, oablokhina commented on src/calculateRentalCost.js
> +    answer = days * 40;
add days * 40 value to a variable, and then use it.

2022-09-06 07:23 UTC, djtyrf312 approved these changes

2023-01-21 16:44 UTC, closed without merging