solution
mate-academy/js_task-transportation-on-vacation pull request #1832
Opened 2022-09-14 14:27 UTC by DimaFlacko

2022-09-16 10:45 UTC, Anna-Borodaienko approved these changes

2022-09-16 10:48 UTC, MAKSOti approved these changes
GJ))

2022-09-16 15:22 UTC, Andr1yK requested changes
[point 5](https://github.com/mate-academy/js_task-transportation-on-vacation/blob/master/checklist.md)

2022-09-20 13:52 UTC, silchyn approved these changes
Cool!

2023-02-20 16:34 UTC, closed without merging