Solution
mate-academy/js_task-transportation-on-vacation pull request #1851
Opened 2022-09-24 05:52 UTC by bagibest

2022-09-25 13:11 UTC, SanyaBratashchuk requested changes

2022-09-25 13:11 UTC, SanyaBratashchuk commented on src/calculateRentalCost.js
> +}
switch true is useless, use if and move all 'magic' numbers to the variables

2022-09-30 16:26 UTC, stanislav-topikha requested changes
You misunderstood previous comment
Move all number to the variables with corresponding names

2022-10-02 17:16 UTC, stanislav-topikha requested changes

2022-10-02 17:16 UTC, stanislav-topikha commented on src/calculateRentalCost.js
> +  } else if (days >= 3) {
```suggestion
  if (days >= bigPeriod) {
    return sum - maxDiscount;
  } else if (days >= smallPeriod) {
```
2 more vars

2022-10-09 12:13 UTC, SanyaBratashchuk approved these changes

2023-12-26 04:06 UTC, closed without merging