Task Done
mate-academy/js_task-transportation-on-vacation pull request #1867
Opened 2022-10-03 11:36 UTC by SalehBUD

2022-10-06 15:35 UTC, TarasHoliuk requested changes

2022-11-08 15:24 UTC, mgrinko requested changes

2022-11-17 09:25 UTC, naziamoff requested changes

2022-11-17 09:59 UTC, naziamoff requested changes
Take a look at the [checklist](https://github.com/mate-academy/js_task-transportation-on-vacation/blob/master/checklist.md) p.3

2022-11-17 10:28 UTC, naziamoff approved these changes
Well done!

2022-11-17 10:28 UTC, naziamoff commented on src/calculateRentalCost.js
> +  }
Looks better this way

```suggestion
  if (days >= 7) {
    return days * price - maxDiscount;
  } 
  
  if (days >= 3) {
    return days * price - minDiscount;
  }
```

2022-11-17 10:32 UTC, SalehBUD commented on src/calculateRentalCost.js
> +  }
Thank you

2026-08-05 04:33 UTC, closed without merging