added solution
mate-academy/js_task-transportation-on-vacation pull request #1929
Opened 2022-10-19 16:10 UTC by kryvets-vadym

2022-10-21 05:39 UTC, Olexandr6 requested changes
Pay attention to the Checklist, looks like you haven't seen it

2022-10-21 05:39 UTC, Olexandr6 commented on src/calculateRentalCost.js
> +  const costsPerDay = 40;
```suggestion
  const carRentCostDaily = 40;
```

2022-10-21 05:39 UTC, Olexandr6 commented on src/calculateRentalCost.js
> +  }
[Checklist](https://github.com/mate-academy/js_task-transportation-on-vacation/blob/master/checklist.md) the 3rd point

2022-10-21 05:39 UTC, Olexandr6 commented on src/calculateRentalCost.js
> +  const threeDaysDiscount = 20;
[Checklist](https://github.com/mate-academy/js_task-transportation-on-vacation/blob/master/checklist.md) the 5th point

2022-10-24 07:21 UTC, denys-danyliuk approved these changes

2024-01-15 14:15 UTC, closed without merging