rentalCost v1.0
mate-academy/js_task-transportation-on-vacation pull request #1957
Opened 2022-10-30 21:09 UTC by Mykola-Hadupiak

2022-10-31 15:28 UTC, DarkMistyRoom requested changes
Proofread the [CHECKLIST](https://github.com/mate-academy/js_task-transportation-on-vacation/blob/master/checklist.md)

2022-10-31 17:36 UTC, Mykola-Hadupiak commented on src/calculateRentalCost.js
> +  }
Oopps, sorry, I didnt see this file.
Thanks

2022-11-01 20:07 UTC, ivanchuk-yurii requested changes

2022-11-01 20:07 UTC, ivanchuk-yurii commented on src/calculateRentalCost.js
> +  const cost = 40;
```suggestion
  const cost = 40 * days;
```
and use without duplication

2022-11-01 20:08 UTC, ivanchuk-yurii approved these changes

2023-11-22 22:21 UTC, closed without merging