Solution
mate-academy/js_task-transportation-on-vacation pull request #1972
Opened 2022-11-09 13:20 UTC by M-Grisha

2022-11-10 07:36 UTC, tetiana-ivanchenko commented on src/calculateRentalCost.js
> +    return Number(days) * 40;
move "magic" numbers to variables.
I mean when someone looks at your code it's not clear what is 40, 20, 50?
also you can create a variable for days * 40.
and why do you need a Number(days)? days is already a number

2022-11-14 07:48 UTC, tetiana-ivanchenko requested changes

2022-11-14 07:48 UTC, tetiana-ivanchenko commented on src/calculateRentalCost.js
> +  }
redundant

2022-11-14 07:48 UTC, tetiana-ivanchenko commented on src/calculateRentalCost.js
> +  }
```suggestion
  return rentCost;
```

2022-11-15 19:54 UTC, AlisaVlasova requested changes

2022-11-15 19:54 UTC, AlisaVlasova commented on src/calculateRentalCost.js
> +  }
цю умову можна видалити, всеодно повертається rentCost
`  if (days < 3) {
    return rentCost;
  }`

2022-11-24 13:56 UTC, M-Grisha commented
Tnx, I fix and understand my mistakes)

2022-11-24 14:42 UTC, tetiana-ivanchenko approved these changes

2023-01-22 01:21 UTC, closed without merging