Solution
mate-academy/js_task-transportation-on-vacation pull request #2060
Opened 2022-11-23 12:10 UTC by miftaha

2022-11-23 14:50 UTC, grslckr requested changes

2022-11-23 14:50 UTC, grslckr commented on src/calculateRentalCost.js
> +  } else {
you should read the checklist about else and variables.
https://github.com/mate-academy/js_task-transportation-on-vacation/blob/master/checklist.md

2022-11-23 15:10 UTC, grslckr approved these changes

2022-11-24 12:36 UTC, mgrinko approved these changes

2026-03-24 15:49 UTC, closed without merging