Solution
mate-academy/js_task-transportation-on-vacation pull request #2158
Opened 2022-12-24 16:49 UTC by sv-dubov

2022-12-27 13:03 UTC, andrieieva-yuliia approved these changes
Nice work 👍

2022-12-27 13:20 UTC, sv-dubov commented on src/calculateRentalCost.js
> +  if (days >= 3 && days < 7) {
Thanks for the review! Maybe in this case it's not a very long line :)

2022-12-27 14:56 UTC, Denchepornyuk requested changes

2022-12-27 14:56 UTC, Denchepornyuk commented on src/calculateRentalCost.js
> +  if (days >= 3 && days < 7) {
you can move check with `days >= 3` under `days >= 7` and then you can remove `days < 7`

2022-12-28 11:30 UTC, Denchepornyuk approved these changes

2023-01-18 11:47 UTC, closed without merging