solution
mate-academy/js_task-transportation-on-vacation pull request #2228
Opened 2023-01-09 10:23 UTC by d-beschastnyi

2023-01-10 09:20 UTC, DarkMistyRoom requested changes
make variables for all 'magic' numbers

2023-01-10 09:20 UTC, DarkMistyRoom commented on src/calculateRentalCost.js
> +  }
you can do the same only with 2 `if`s

2023-01-16 19:08 UTC, agniya-i requested changes

2023-01-24 19:16 UTC, Anastasiia-Svintsova approved these changes

2024-08-06 18:05 UTC, closed without merging