Solution
mate-academy/js_task-transportation-on-vacation pull request #2307
Opened 2023-02-06 10:10 UTC by YuliiaUmantseva

2023-02-06 16:51 UTC, Viktor-Kost requested changes

2023-02-06 16:51 UTC, Viktor-Kost commented on src/calculateRentalCost.js
> +  let sum = 0;
```suggestion
  let sum = dayCost * days;
```

2023-02-06 16:51 UTC, Viktor-Kost commented on src/calculateRentalCost.js
> +  } else {
This `days < 3 `condition will be redundant
```suggestion
```

2023-02-06 16:51 UTC, Viktor-Kost commented on src/calculateRentalCost.js
> +      sum = (dayCost * days) - threeDaysDiscount;
```suggestion
      sum -= threeDaysDiscount;
```

2023-02-06 16:51 UTC, Viktor-Kost commented on src/calculateRentalCost.js
> +    }
```suggestion
  if (days >= 7) {
    sum -= sevenDaysDiscount;
  }
```

2023-02-07 08:35 UTC, tetiana-ivanchenko requested changes

2023-02-07 08:35 UTC, tetiana-ivanchenko commented on src/calculateRentalCost.js
> +    if (days >= 7) {
```suggestion
  } else if (days >= 7) {
```

2023-02-07 08:36 UTC, vlad-demchuk requested changes

2023-02-07 08:36 UTC, vlad-demchuk commented on src/calculateRentalCost.js
> +  if (days >= 3 && days < 7) {
let's do it this way to avoid redundant conditional
```
if (days < 3) {
  }

  if (days < 7) {
  }

  if (days >= 7) {
  }
```

2023-02-07 15:36 UTC, IvanFesenko approved these changes

2023-10-26 09:36 UTC, closed without merging