solution
mate-academy/js_task-transportation-on-vacation pull request #2536
Opened 2023-03-28 15:54 UTC by kq333

2023-03-29 02:34 UTC, SuaBy514 approved these changes

2023-03-29 08:00 UTC, michalcywka requested changes
We don't want magic numbers here :) Checklist point 1 and 4

2023-03-30 08:48 UTC, michalcywka approved these changes

2023-03-30 08:49 UTC, michalcywka requested changes

2023-03-30 08:49 UTC, michalcywka commented on src/calculateRentalCost.js
> +    return days * price;
`days * price` is repeated, can me move it to a variable? :)

2023-03-31 09:11 UTC, michalcywka requested changes

2023-03-31 09:11 UTC, michalcywka commented on src/calculateRentalCost.js
> +  if (days >= 7) {
Do we really need this if here?

2023-04-03 07:46 UTC, d-wasilewski requested changes

2023-04-03 07:46 UTC, d-wasilewski commented on src/calculateRentalCost.js
> +  if (days >= 7) {
we don't. It's checklist point 3

2023-10-03 20:29 UTC, closed without merging