Solution
mate-academy/js_task-transportation-on-vacation pull request #2581
Opened 2023-04-11 14:11 UTC by Nikita211112

2023-04-11 18:04 UTC, polosanya requested changes
Almost done! Let's improve your code a bit)
Create variables for all main values (40, 50, 20 etc.)

2023-04-11 18:04 UTC, polosanya commented on src/calculateRentalCost.js
> +  let sum = 0;
Create a const variable for `days * 40`. You duplicate this value a lot
![image](https://user-images.githubusercontent.com/96409563/231249749-375c5ee4-4d87-422a-bf44-bfb96cf3927e.png)

2023-04-11 18:04 UTC, polosanya commented on src/calculateRentalCost.js
> +    sum = days * 40;
No need to use if...else. It makes your code a bit complicated. 
Just return the full price immediately if the condition is true
![image](https://user-images.githubusercontent.com/96409563/231250423-08048199-8970-4180-b3f8-c434850f81c1.png)

2023-04-14 16:34 UTC, loralevitska approved these changes
🔥

2023-04-16 17:54 UTC, closed without merging