Fs jul19 alex andrutskii solution
mate-academy/js_task-transportation-on-vacation pull request #26
Opened 2019-08-12 17:19 UTC by aleks-and

2019-08-12 17:21 UTC, danheim requested changes

2019-08-12 17:21 UTC, danheim commented on src/calculateRentalCost.js
> +    return days * price;
else тут не нужен, можно сразу return (на новой строке, отделенный пустой строкой)
действие `days * price` повторяется, попробуй исправить ситуацию

2019-08-12 19:44 UTC, aleks-and commented on src/calculateRentalCost.js
> +    return days * price;
Roger that!
How about the next one? Now we can add as many discounts as we want (not caring about the order).

2019-08-13 10:37 UTC, YuriiHoliuk requested changes
Looks like you try to create reusable, modular solution, that's great, but it is over complicated, try to write as simple code as you can

To0 make solution modular, with some utils in separate functions, these functions should be written separately from main function for you and other developers can reuse them

2019-08-13 10:37 UTC, YuriiHoliuk commented on src/calculateRentalCost.js
> +  let discountsList = [];
use let only when necessary, here const will be enough

2019-08-13 10:37 UTC, YuriiHoliuk commented on src/calculateRentalCost.js
> +  class Discount {
class is really overkill here

2019-08-13 10:37 UTC, YuriiHoliuk commented on src/calculateRentalCost.js
> +  function createDiscountList(dList) {
do not declare functions inside function(There are reasons for it but not in this case)

2019-08-13 10:37 UTC, YuriiHoliuk commented on src/calculateRentalCost.js
> +      discountsList.push(new Discount(dItem[0], dItem[1]));
functions should be pure and do not use variables in closure

2019-08-13 10:37 UTC, YuriiHoliuk commented on src/calculateRentalCost.js
> +    dList.forEach(function(dItem) {
use arrow functions for callbacks

2019-08-13 10:37 UTC, YuriiHoliuk commented on src/calculateRentalCost.js
> +      discountsList.push(new Discount(dItem[0], dItem[1]));
dList and discountsList, looks over complicated

2019-08-13 10:37 UTC, YuriiHoliuk commented on src/calculateRentalCost.js
> +  function compareDiscount(a, b) {
There are simpler way to compare 2 numbers

2019-08-13 10:37 UTC, YuriiHoliuk commented on src/calculateRentalCost.js
> +        break;
do not use break, it is hard to maintain and bad practice

2019-08-13 10:37 UTC, YuriiHoliuk commented on src/calculateRentalCost.js
> +    for (let i = 0; i < discountsList.length; i++) {
do not use for loop for arrays use array methods instead

2019-08-13 10:37 UTC, YuriiHoliuk commented on src/calculateRentalCost.js
> +      if (rentalDays >= discountsList[i]['days']) {
use dynamic property access only when neccessary

2019-08-13 10:37 UTC, YuriiHoliuk commented on src/calculateRentalCost.js
> +  function rentalCost(rentalDays, priceForDay) {
function name should start with a verb

2019-08-13 10:37 UTC, YuriiHoliuk commented on src/calculateRentalCost.js
> +  createDiscountList([[3, 20], [7, 50]]);
maybe array of array is not the best data structure for this propose?

2019-08-13 18:10 UTC, aleks-and commented
> Looks like you try to create reusable, modular solution, that's great, but it is over complicated, try to write as simple code as you can
> 
> To0 make solution modular, with some utils in separate functions, these functions should be written separately from main function for you and other developers can reuse them

Got it. Thanks!
Remaking the current code according to your comments is too difficult for me at the moment, therefore, I just solve the task.

2019-08-14 10:34 UTC, YuriiHoliuk approved these changes

2026-01-17 14:35 UTC, closed without merging