Solution
mate-academy/js_task-transportation-on-vacation pull request #2695
Opened 2023-05-07 16:11 UTC by Shevtsooov

2023-05-07 18:26 UTC, amashutikov approved these changes
Good job, in my opinion its better to create const values for discounts.

2023-05-08 07:26 UTC, silchyn requested changes

2023-05-08 07:26 UTC, silchyn commented on src/calculateRentalCost.js
> +  if (days < 3) {
what is `3`?

2023-05-08 07:26 UTC, silchyn commented on src/calculateRentalCost.js
> +    totalAmount = (rentPerDay * days) - threeDaysDiscount;
that's hard to understand

2023-05-08 09:41 UTC, serentinos approved these changes
Good job!

2023-05-08 16:16 UTC, silchyn requested changes
check checklist rule `#3`

2023-05-08 16:16 UTC, silchyn commented on src/calculateRentalCost.js
> +  if (days < 3) {
still magic number

2023-05-08 17:21 UTC, Shevtsooov commented
@silchyn Thank you for the review, now I got what you meant.
Corrected!

2023-05-09 10:02 UTC, silchyn approved these changes

2024-05-05 10:54 UTC, closed without merging