solution
mate-academy/js_task-transportation-on-vacation pull request #2725
Opened 2023-05-08 14:32 UTC by liza-strykharchuk

2023-05-08 16:00 UTC, Viktor-Kost requested changes

2023-05-08 17:00 UTC, Viktor-Kost requested changes
Good job!
Looks much better. 
Some minor fixed needed

2023-05-08 17:00 UTC, Viktor-Kost commented on src/calculateRentalCost.js
> +  return result - fifty;
it'd be better to exchange like this
```suggestion
  if (days >= 7) {
    return rentalCost - proDiscount;
  }

  if (days >= 3) {
    return rentalCost - baseDiscount;
  }

  return rentalCost;
```

2023-05-08 18:12 UTC, Viktor-Kost approved these changes
Perfect!

2023-05-10 18:12 UTC, nazarmatsevych approved these changes

2023-05-10 19:01 UTC, nazarmatsevych requested changes
* test

2023-05-10 19:36 UTC, closed without merging