add task solution
mate-academy/js_task-transportation-on-vacation pull request #2729
Opened 2023-05-08 16:01 UTC by PanyaPrimal

2023-05-10 07:35 UTC, 33Orange requested changes
Good job.

A few moments:
- Use variables for the main values so that you can reuse them and give them descriptive names. For now it's not clear what is 40, 50 and 20
- You should return the value **immediately** in if statements. And don't use else after return statement. If return is performed - code after it won't be executed anyway. 

```
if (condition) {
  return a;
}
if (condition) {
  return b;
}
return c;
```

2023-05-10 07:35 UTC, 33Orange commented on src/calculateRentalCost.js
> +    discount = 20;
Consider using a constant variable for the discount amount for 3 to 6 days.

2023-05-10 07:35 UTC, 33Orange commented on src/calculateRentalCost.js
> +    discount = 50;
Consider using a constant variable for the discount amount for 7 or more days.

2023-05-10 07:35 UTC, 33Orange commented on src/calculateRentalCost.js
> +  return (days * 40) - discount;
Consider using a constant variable for the daily rental cost.

2023-05-15 08:40 UTC, naziamoff requested changes
a couple of things left and we're good to go 🚀

2023-05-15 08:40 UTC, naziamoff commented on src/calculateRentalCost.js
> +  const discount7OrMoreDays = 50;
- we never use numbers in the name of our variables
- what if we gonna change the policy and the discount 20 will be applied starting with the second day and ending on the fifth? You gonna need to change the variable name in all the usage places.

So let's think of more reusable names for those variables, more generic

2023-05-15 08:40 UTC, naziamoff commented on src/calculateRentalCost.js
> +  }
if you start checking for `if days >= 7` - you won't need to checks in this `if`

2023-05-15 08:40 UTC, naziamoff commented on src/calculateRentalCost.js
> +    return days * dailyRentalCost - discount7OrMoreDays;
As days * dailyRentalCost is always a constant- I would create a separate variable for that

2023-05-22 07:40 UTC, silchyn requested changes

2023-05-22 07:40 UTC, silchyn commented on src/calculateRentalCost.js
> +    case days >= 7:
what is `7`?

2023-05-29 06:13 UTC, 33Orange approved these changes
Good job

2023-05-29 06:13 UTC, 33Orange commented on src/calculateRentalCost.js
> +  if (days >= 7) {
You can create variable for number 7. For example `daysForExtraDiscount`

2023-05-29 06:13 UTC, 33Orange commented on src/calculateRentalCost.js
> +  if (days >= 3 && days < 7) {
Same here.

2025-12-18 12:06 UTC, closed without merging