My first forked solution
mate-academy/js_task-transportation-on-vacation pull request #2926
Opened 2023-06-29 18:48 UTC by WaveOfDandelions

2023-07-21 09:47 UTC, JoyCoffeeAddict requested changes

2023-07-21 09:47 UTC, JoyCoffeeAddict commented on src/calculateRentalCost.js
> +  return result;
Checklist point 2, use `const`s for constant values. Also checklist point 5. Try to come up with idea how to avoid writing else if.

2023-07-25 06:44 UTC, choeqq requested changes
Waiting for any updates @WaveOfDandelions 👀

2023-07-26 02:51 UTC, WaveOfDandelions commented
> Waiting for any updates @WaveOfDandelions 👀

Nie wiem co tu zminiac, poniewasz result nie moze byc const, bo zmieniam znaczenie w trakcie dzialania funkcje!
Ja tez myslie ze ten else if tu bardzo przydatny i czytelny

2023-07-26 06:11 UTC, choeqq approved these changes

2024-06-25 23:15 UTC, closed without merging