Develop
mate-academy/js_task-transportation-on-vacation pull request #3039
Opened 2023-07-27 16:16 UTC by Valentyn-Bilyk

2023-07-28 12:38 UTC, yar0man approved these changes
Great job!

2023-07-28 14:18 UTC, Vannnkof approved these changes
Perfect!

2023-07-31 09:47 UTC, alexander-ignatow reviewed
LGTM for now 👍 

Two points
1) mind the grammar!
2) You should declare constants outside the body of the function where possible - see the comments below

2023-07-31 09:47 UTC, alexander-ignatow commented on src/calculateRentalCost.js
> +  const PRISE_OF_DAY = 40;
In your case it is `price`, not `prise`

2023-07-31 13:59 UTC, Moroz-Dmytro requested changes
Check previous mentor's comments

2023-07-31 14:00 UTC, Moroz-Dmytro commented on src/calculateRentalCost.js
> +  const RESULT_PRISE = days * PRISE_OF_DAY;
Also
It is customary to name static variables with a capital letter, if something is calculated in the variable, it is better to name it using the usual camelCase.

2023-07-31 15:42 UTC, tiserett requested changes

2023-07-31 15:42 UTC, tiserett commented on src/calculateRentalCost.js
> +const PRICE_OF_DAY = 40;
PRICE_PER_DAY

2023-07-31 15:42 UTC, tiserett commented on src/calculateRentalCost.js
> +  const resultPrice = days * PRICE_OF_DAY;
I guess basePrice is a better name

2023-07-31 18:56 UTC, Anna-Tkachenko approved these changes
⭐️

2026-01-24 21:50 UTC, closed without merging