task solution
mate-academy/js_task-transportation-on-vacation pull request #3486
Opened 2023-10-30 10:36 UTC by Timi2424

2023-10-30 13:36 UTC, web3-sorcerer commented
Hi Tymon, in order to pass your tests you have to change the line inside test.yml file:
'node-version: [14.x]' instead of [12.x] because as you can see your build was tested for that version.

2023-10-30 13:44 UTC, web3-sorcerer requested changes
Your code lacks the ability to calculate the cost of rent when it's lower than 3 days + the thing I mentioned previously about test.yml

2023-10-30 14:05 UTC, Timi2424 commented
Thank you, I missed these steps, hovewer the code should work fine. It calculates the cost on the beginning and then substract discount accordingly

2023-11-03 07:46 UTC, mvjl000 requested changes

2023-11-03 07:46 UTC, mvjl000 commented on src/calculateRentalCost.js
We need some improvements here. Read the checklist and make sure to apply its rules to your code ;)

Especially remember about constants (for values like base price, long term, short term, discounts etc) - those should be in uppercased snake case. It would be also good to put them outside of the function so you could use them in other places in your code.

Instead of using let, create a const and then inside of if statements, simply return the proper calculation

2023-11-03 09:53 UTC, mvjl000 approved these changes
Perfect!

2024-07-05 16:50 UTC, closed without merging