add solution
mate-academy/js_task-transportation-on-vacation pull request #3736
Opened 2023-12-24 00:04 UTC by happytravels38

2023-12-24 08:55 UTC, Andriy-Shymkiv requested changes
create variables for discounts `20` and `50`

2023-12-31 07:04 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's improve your code

2023-12-31 07:04 UTC, volodymyr-soltys97 commented on src/calculateRentalCost.js
> +  }
Fix it everywhere
```suggestion

  if (days < 3) {
    return COST_PER_DAY * days;
  }
```

2024-01-02 18:47 UTC, loralevitska approved these changes
Well done)

2025-06-16 18:38 UTC, closed without merging