Develop
mate-academy/js_task-transportation-on-vacation pull request #3950
Opened 2024-02-18 13:31 UTC by iFedyna

add solution

2024-02-18 13:38 UTC, anastasiiavorobiova requested changes
Great work! Almost done!

2024-02-18 13:38 UTC, anastasiiavorobiova commented on src/calculateRentalCost.js
> +  const SHORT_TERM_DISCOUNT = 20;
```suggestion
  const SHORT_TERM_DISCOUNT = 20;
  const basePrice = days * PRICE_PER_DAY;
```

2024-02-18 13:38 UTC, anastasiiavorobiova commented on src/calculateRentalCost.js
> +    return days * PRICE_PER_DAY - LONG_TERM_DISCOUNT;
```suggestion
    return basePrice - LONG_TERM_DISCOUNT;
```

2024-02-18 13:38 UTC, anastasiiavorobiova commented on src/calculateRentalCost.js
> +    return days * PRICE_PER_DAY - SHORT_TERM_DISCOUNT;
```suggestion
    return basePrice - SHORT_TERM_DISCOUNT;
```

2024-02-18 13:38 UTC, anastasiiavorobiova commented on src/calculateRentalCost.js
> +  return days * PRICE_PER_DAY;
```suggestion
  return basePrice;
```

2024-02-20 07:38 UTC, etojeDenys approved these changes
lgtm

2025-09-04 13:42 UTC, closed without merging