calculateRentalCost
mate-academy/js_task-transportation-on-vacation pull request #3994
Opened 2024-02-26 12:29 UTC by svyatoslavPy

# Transportation on Vacation

After a hard quarter in the office you decide to get some rest on a vacation. So you
will book a flight for you and your family and try to leave all the mess behind you.

You will need a rental car in order for you to get around in your vacation. The
manager of the car rental makes you some good offers.

Every day you rent the car costs `$40`. If you rent the car for `7` or more days, you
get `$50` off your total. Alternatively, if you rent the car for `3` or more days,you
get `$20` off your total.

Implement `calculateRentalCost` function that returns the total amount for different
number of days.

Examples:
```js
calculateRentalCost(1); // 40
calculateRentalCost(3); // 100
calculateRentalCost(7); // 230
```

## Instructions
**Read [the guideline](https://mate-academy.github.io/js_task-guideline/) before start**

## ❗️❗️❗️ DON'T FORGET TO PROOFREAD YOUR CODE WITH [CHECKLIST](checklist.md) BEFORE SENDING YOUR PULL REQUEST❗️❗️❗️

2024-02-26 13:10 UTC, lerastarynets requested changes
Nice start! Let's fix the solution according to the checklist

2024-02-26 13:10 UTC, lerastarynets commented on src/calculateRentalCost.js
> +  if (days >= 7) {
pls move ALL numbers to consts and use here

2024-02-26 13:55 UTC, anastasiiavorobiova requested changes
GJ! Almost done!

2024-02-26 13:55 UTC, anastasiiavorobiova commented on src/calculateRentalCost.js
> +  const MIDDLE_TERM = 6;
```suggestion

```

2024-02-26 13:55 UTC, anastasiiavorobiova commented on src/calculateRentalCost.js
> +  if (days >= LOW_TERM && days <= MIDDLE_TERM) {
```suggestion
  if (days >= LOW_TERM && days < LONG_TERM) {
```

2024-02-27 11:51 UTC, lerastarynets approved these changes
You've got this, keep pushing forward!

2024-09-28 18:27 UTC, closed without merging