Task-transportation-on-vacation solved.
mate-academy/js_task-transportation-on-vacation pull request #748
Opened 2021-08-02 12:23 UTC by Andrii-Pinchuk

2021-08-02 13:39 UTC, Moroz-Dmytro approved these changes

2021-08-03 09:36 UTC, Ihor-Karpyn requested changes
Give a more meaningful name and don't forgetting gold rule of developers

2021-08-03 09:36 UTC, Ihor-Karpyn commented on src/calculateRentalCost.js
> +  let count = 0;
count of what?

2021-08-03 09:36 UTC, Ihor-Karpyn commented on src/calculateRentalCost.js
> +    count = 40 * days - 20;
`40 * days` don't repeat yourself

2021-08-03 09:36 UTC, Ihor-Karpyn commented on src/calculateRentalCost.js
> +    count = 40 * days - 50;
`40 * days` don't repeat yourself

2021-08-03 10:42 UTC, Ihor-Karpyn approved these changes
Great, but you can simplify more

2021-08-03 10:42 UTC, Ihor-Karpyn commented on src/calculateRentalCost.js
> +  return totalSumForAllDays;
```suggestion
  if (days >= 7) {
    return totalSumForAllDays - discountFor7days;
  }
   if (days >= 3) {
    retunr totalSumForAllDays - discountFor3days;
  }

  return totalSumForAllDays;
```

2025-10-29 15:56 UTC, closed without merging