Solution
mate-academy/js_task-transportation-on-vacation pull request #985
Opened 2021-11-27 06:14 UTC by YevhS

2021-11-29 09:34 UTC, danylo-onishchuk requested changes

2021-11-29 09:34 UTC, danylo-onishchuk commented on src/calculateRentalCost.js
> +  return days * 40 - 50;
помести цифры в переменные с логичными названиями, чтоб было понятно, что происходит в задаче

2021-11-29 19:13 UTC, YevhS commented on src/calculateRentalCost.js
> +  return days * 40 - 50;
Изменил

2021-12-06 19:34 UTC, closed without merging

2021-12-06 19:34 UTC, YevhS commented
Waited too long